server:
  port: 10000

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10087/eureka

zuul:
  prefix: /api

  # 配置微服务与路由的映射
#  routes:
